[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"


[window]
opacity = 0.7


[colors.primary]
background = "#24273a"
foreground = "#cad3f5"


[colors.cursor]
cursor = '#F4DBD6'


[colors.vi_mode_cursor]
cursor = '#B7BDF8'


[colors.search.matches]
background = '#A5ADCB'


[colors.search.focused_match]
background = '#A6DA95'


[colors.footer_bar]
background = '#A5ADCB'


[colors.hints.start]
background = '#EED49F'


[colors.hints.end]
background = '#A5ADCB'


[colors.selection]
background = '#F4DBD6'


[colors.normal]
black = '#494D64' # surface1
red = '#ED8796' # red
green = '#A6DA95' # green
yellow = '#EED49F' # yellow
blue = '#8AADF4' # blue
magenta = '#F5BDE6' # pink
cyan = '#8BD5CA' # teal
white = '#B8C0E0' # subtext1


[colors.bright]
black = '#5B6078' # surface2
red = '#ee99a0' # maroon
green = '#b8e1aa' # bright green
yellow = '#f1ddb2' # bright yellow
blue = '#7dc4e4' # sapphire
magenta = '#f7caeb' # bright pink
cyan = '#91d7e3' # sky
white = '#A5ADCB' # subtext0

