format = """
[ ░▒▓](pbg2)\
[   ](fg:text0 bg:pbg2)\
[ ](fg:pbg2 bg:pbg3)\
$username\
[   ](fg:pbg0 bg:pbg3)\
$hostname\
$nix_shell\
[ ](fg:pbg3 bg:pbg4)\
$directory\
[ ](fg:pbg4 bg:pbg5)\
$git_branch\
[󰄛 ](fg:pbg0 bg:pbg5)\
[ ](fg:pbg5 bg:transparent)\
$python\
$character
"""


palette = 'random'


[palettes.random]
text0 = "#cad3f5"
text1 = "#b7bdf8"
pbg0 = "#212337"
pbg1 = "#403c64"
pbg2 = "#596399"
pbg3 = "#748cd6"
pbg4 = "#a1abe0"
pbg5 = "#b4a4f4"
pbg6 = "#e5a2f0"
pbg7 = "#ef43fa"
base00 = "#ed8796"
base01 = "#f5a97f"
base02 = "#eed49f"
base03 = "#a6da95"
base04 = "#8bd5ca"
base05 = "#8aadf4"
base06 = "#c6a0f6"
base07 = "#f0c6c6"


[username]
show_always = true
style_user = "fg:pbg0 bg:pbg3"
format = '[$user]($style)'


[hostname]
ssh_only = false
style = "fg:pbg0 bg:pbg3"
format = '[$hostname ]($style)'


[nix_shell]
disabled = false
style = "fg:pbg0 bg:pbg3"
impure_msg = '[impure](fg:bold base00 bg:pbg3)'
pure_msg = '[pure](fg:bold base03 bg:pbg3)'
unknown_msg = '[unknown](fg:bold base02 bg:pbg3)'
format = '[ $state( \($name\)) ]($style)'


[directory]
style = "fg:pbg0 bg:pbg4"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"


[git_branch]
symbol = ""
style = "bg:pbg5"
format = '[[$symbol $branch ](fg:pbg0 bg:pbg5)]($style)'


[python]
symbol = ''


[character]
format = '$symbol '

