format = """
[ ░▒▓](base02)\
[   ](fg:base00 bg:base02)\
[ ](fg:base02 bg:base03)\
$username\
[@](fg:base00 bg:base03)\
$hostname\
$nix_shell\
[ ](fg:base03 bg:base04)\
$directory\
[ ](fg:base04 bg:base06)\
$git_branch\
[󰄛 ](fg:base00 bg:base06)\
[ ](fg:base06 bg:transparent)\
$character
"""


palette = 'moonlight'


[palettes.moonlight]
base00 = "#212337"
base01 = "#403c64"
base02 = "#596399"
base03 = "#748cd6"
base04 = "#a1abe0"
base05 = "#a3ace1"
base06 = "#b4a4f4"
base07 = "#ef43fa"
base08 = "#ff5370"
base09 = "#f67f81"
base0A = "#ffc777"
base0B = "#2df4c0"
base0C = "#04d1f9"
base0D = "#40ffff"
base0E = "#b994f1"
base0F = "#ecb2f0"


[username]
show_always = true
style_user = "fg:base00 bg:base03"
format = '[$user]($style)'


[hostname]
ssh_only = false
style = "fg:base00 bg:base03"
format = '[$hostname ]($style)'


[nix_shell]
disabled = false
style = "fg:base00 bg:base03"
impure_msg = '[impure](fg:bold red bg:base03)'
pure_msg = '[pure](fg:bold green bg:base03)'
unknown_msg = '[unknown](fg:bold yellow bg:base03)'
format = '[via $state( \($name\)) ]($style)'


[directory]
style = "fg:base00 bg:base04"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"


[git_branch]
symbol = ""
style = "bg:base06"
format = '[[$symbol $branch ](fg:base00 bg:base06)]($style)'


[character]
format = '$symbol '

